version: "3"

tasks:
  clean:
    description: Clean up the project
    cmds:
      - rm -rf dist
  bundle:
    description: Create a self-contained executable
    cmds:
      - |
        task clean
        mkdir -p dist
        bun build ./index.ts --compile --target=bun-linux-x64 --outfile=dist/crustomize-linux-x64
        bun build ./index.ts --compile --target=bun-darwin-arm64 --outfile=dist/crustomize-darwin-x64
  install:
    description: Install the project in linux
    cmds:
      - cp -f dist/crustomize-linux-x64 $HOME/.local/bin/crustomize