name: Build and Test

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Tests
        run: |
          bun i
          bunx tsc
          AWS_REGION=us-east-1 bun test