- ParameterKey: EnvironmentName
  ParameterValue: {{ values.EnvironmentName }}
- ParameterKey: VpcId
  ParameterValue: { { lookup values.VpcStackName "VPC" } }
- ParameterKey: Account
  ParameterValue: {{ env.account }}
- ParameterKey: Region
  ParameterValue: {{ env.region }}