AWSTemplateFormatVersion: '2010-09-09'
Description: Base Lambda Function

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: <%= FunctionName %>
      Runtime: <%= Runtime %>
      Handler: <%= Handler %>
      MemorySize: <%= MemorySize %>
      Timeout: <%= Timeout %>
      Role: !GetAtt LambdaExecutionRole.Arn
      <% if (VpcConfig && VpcConfig.subnetIds && VpcConfig.securityGroupIds) { %>
      VpcConfig:
        SecurityGroupIds:
<% VpcConfig.securityGroupIds.forEach(function(id){ %>
          - <%= id %>
<% }); %>
        SubnetIds:
<% VpcConfig.subnetIds.forEach(function(id){ %>
          - <%= id %>
<% }); %>
      <% } %>
      <%
        const envVars = EnvironmentVariables || {};
        const keys = Object.keys(envVars);
        if (keys.length > 0) {
      %>
      Environment:
        Variables:
<% keys.forEach(function(key){ %>
          <%= key %>: "<%= envVars[key] %>"
<% }); %>
      <% } %>
    DependsOn:
      - LambdaLogGroup # Ensures Log Group is created before Lambda
      # The policy attachment might need an explicit DependsOn if not handled by role reference
      # - LambdaExecutionPolicy

Outputs:
  FunctionName:
    Description: Name of the Lambda Function
    Value: !Ref MyLambdaFunction
  FunctionArn:
    Description: ARN of the Lambda Function
    Value: !GetAtt MyLambdaFunction.Arn
