AWSTemplateFormatVersion: '2010-09-09'
Description: Base Monitoring for Lambda Function

Conditions:
  MonitoringEnabled: !Equals [ "<%= MonitoringEnabled %>", "true" ]

Resources:
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: MonitoringEnabled
    Properties:
      AlarmName: !Sub "${FunctionName}-Errors"
      AlarmDescription: "Alarm for Lambda function errors"
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref MyLambdaFunction # Assumes the Lambda function's logical ID is MyLambdaFunction
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      # SNS Topic for notifications can be added here or via overlay
      # AlarmActions:
      #   - !Ref SnsTopicArn

Outputs:
  ErrorAlarmName:
    Description: Name of the Lambda error alarm
    Condition: MonitoringEnabled
    Value: !Ref LambdaErrorAlarm
